version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:17-alpine
    container_name: cv-management-db
    environment:
      POSTGRES_DB: cv_management
      POSTGRES_USER: root
      POSTGRES_PASSWORD: secret
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/main_service/internal/database/schema.sql:/docker-entrypoint-initdb.d/01-schema.sql
      # Đã loại bỏ file insert_mock_data.sql
    networks:
      - cv-management-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Backend Service Instance 1
  app1:
    build: ./backend/main_service
    container_name: cv-management-app1
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=root
      - DB_PASSWORD=secret
      - DB_NAME=cv_management
      - SERVER_PORT=8080
      - JWT_SECRET=your-super-secret-jwt-key-here-make-it-long-and-secure
      - AI_SERVICE_URL=http://ai-service:8000
      - ENV=production
    expose:
      - "8080"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - cv-management-network
    volumes:
      - ./uploads:/app/uploads
    restart: unless-stopped

  # Backend Service Instance 2
  app2:
    build: ./backend/main_service
    container_name: cv-management-app2
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=root
      - DB_PASSWORD=secret
      - DB_NAME=cv_management
      - SERVER_PORT=8080
      - JWT_SECRET=your-super-secret-jwt-key-here-make-it-long-and-secure
      - AI_SERVICE_URL=http://ai-service:8000
      - ENV=production
    expose:
      - "8080"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - cv-management-network
    volumes:
      - ./uploads:/app/uploads
    restart: unless-stopped

  # Backend Service Instance 3
  app3:
    build: ./backend/main_service
    container_name: cv-management-app3
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=root
      - DB_PASSWORD=secret
      - DB_NAME=cv_management
      - SERVER_PORT=8080
      - JWT_SECRET=your-super-secret-jwt-key-here-make-it-long-and-secure
      - AI_SERVICE_URL=http://ai-service:8000
      - ENV=production
    expose:
      - "8080"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - cv-management-network
    volumes:
      - ./uploads:/app/uploads
    restart: unless-stopped

  # Caddy Reverse Proxy
  caddy:
    image: caddy:2-alpine
    container_name: cv-management-caddy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
      - caddy_logs:/var/log/caddy
    depends_on:
      - app1
      - app2
      - app3
    networks:
      - cv-management-network
    restart: unless-stopped

  # AI Service (Python FastAPI)
  ai-service:
    build: ./backend/ai_service
    container_name: cv-management-ai
    environment:
      - AZURE_OPENAI_API_KEY=${AZURE_OPENAI_API_KEY}
      - AZURE_OPENAI_ENDPOINT=${AZURE_OPENAI_ENDPOINT}
      - AZURE_OPENAI_DEPLOYMENT_NAME=${AZURE_OPENAI_DEPLOYMENT_NAME}
      - AZURE_OPENAI_API_VERSION=2024-02-15-preview
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=root
      - DB_PASSWORD=secret
      - DB_NAME=cv_management
    ports:
      - "8000:8000"
    networks:
      - cv-management-network
    volumes:
      - ./uploads:/app/uploads
    restart: unless-stopped

  # Frontend (Next.js)
  frontend:
    build: ./frontend
    container_name: cv-management-frontend
    environment:
      - NEXT_PUBLIC_API_URL=http://167.71.199.165/api
      - NODE_ENV=production
    ports:
      - "3000:3000"
    depends_on:
      - caddy
    networks:
      - cv-management-network
    restart: unless-stopped

volumes:
  postgres_data:
  uploads:
  caddy_data:
  caddy_config:
  caddy_logs:

networks:
  cv-management-network:
    driver: bridge
